import style from '@/app/global.module.css'
import NavBar from '@/app/components/navBar/NavBar';
import RedesSociales from './components/redesSocialesIcons/RedesSociales';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={style.body}>
        <NavBar></NavBar>
        {children}
        <RedesSociales />
      </body>
    </html>
  )
}
