import { Inter } from 'next/font/google'
import style from '../../styles/main.module.css'
import NavBar from '@/app/components/NavBar'; 

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={style.body}>
        <NavBar></NavBar>
        {children}
        </body>
    </html>
  )
}
